"""
Play and Render — Sutton & Barto Example 4.1

This file connects:

    RL Environment
        ↓
    Current Policy
        ↓
    Policy Evaluation
        ↓
    Policy Improvement
        ↓
    GridWorld Renderer

The renderer does NOT perform learning.

The RL environment and dynamic-programming algorithms compute
the policy. The renderer only demonstrates the behavior of the
current policy.
"""

import random
import time
from math import isclose

from grid_nxn_world import GridWorld
from play_4x4_world_game.environment import Action, GridWorld4x4
from play_4x4_world_game.policy import EquiprobableRandomPolicy, Policy
from play_4x4_world_game.policy_evaluation import iterative_policy_evaluation
from play_4x4_world_game.policy_improvement import improve_greedy_policy
from play_4x4_world_game.policy_iteration import check_policies_equal
from play_4x4_world_game.utils import state_to_position

# ---------------------------------------------------------
# Demo configuration
# ---------------------------------------------------------


MAX_EPISODE_STEPS = 40

MOVE_DISPLAY_SECONDS = 0.45
START_DISPLAY_SECONDS = 0.5
END_DISPLAY_SECONDS = 1.0

GAMMA = 1.0
THETA = 1e-6


def get_random_start_state() -> int:
    return random.choice(range(16))


# ---------------------------------------------------------
# Policy action sampling
# ---------------------------------------------------------


def choose_action(
    env: GridWorld4x4,
    policy: Policy,
    state: int,
) -> Action:
    """
    Sample one action according to π(a|s).

    Works for both:
        - EquiprobableRandomPolicy
        - improved greedy policies
    """

    actions: list[Action] = []
    probabilities: list[float] = []

    for action in env.actions:
        probability = policy.probability(
            state,
            action,
        )

        if probability > 0.0:
            actions.append(action)
            probabilities.append(probability)

    if not actions:
        raise RuntimeError(
            f"Policy has no available action " f"for nonterminal state {state}."
        )

    return random.choices(
        actions,
        weights=probabilities,
        k=1,
    )[0]


# ---------------------------------------------------------
# Rendering helpers
# ---------------------------------------------------------


def render_for(
    world: GridWorld,
    seconds: float,
) -> bool:
    """
    Continue rendering for a specified amount of time.

    Returns False if the user closes the window.
    """

    end_time = time.perf_counter() + seconds

    while time.perf_counter() < end_time:
        if not world.render():
            return False

    return True


def show_state(
    world: GridWorld,
    state: int,
    grid_size: int,
    *,
    animate: bool = True,
) -> None:
    """Move the rendered robot to the given RL state."""

    x, y = state_to_position(
        state,
        grid_size,
    )

    world.robot_set_position(
        x,
        y,
        animate=animate,
    )


# ---------------------------------------------------------
# Play one episode
# ---------------------------------------------------------


def play_episode(
    env: GridWorld4x4,
    policy: Policy,
    world: GridWorld,
    start_state: int,
    iteration: int,
) -> bool:
    """
    Demonstrate one episode generated by the current policy.

    The episode itself does NOT train the policy.
    It only shows visually what the current policy does.
    """

    state = start_state

    print()
    print(f"Playing policy from iteration {iteration} " f"starting at state {state}")

    # Start immediately at the selected initial state.
    show_state(
        world,
        state,
        env.GRID_SIZE,
        animate=False,
    )

    if not render_for(
        world,
        START_DISPLAY_SECONDS,
    ):
        return False

    for step_number in range(1, MAX_EPISODE_STEPS + 1):

        if env.is_terminal(state):
            print("-" * 50)
            print(f"Episode Terminated: {state}")
            state = get_random_start_state()
            print(f"Restarting next episode: from state: {state}")
            print("-" * 50)

        action = choose_action(
            env,
            policy,
            state,
        )

        next_state, reward, terminated = env.step(
            state,
            action,
        )

        print(
            f"step={step_number:02d} | "
            f"state={state:2d} | "
            f"action={action.name:<5} | "
            f"next={next_state:2d} | "
            f"reward={reward:4.1f}"
        )

        show_state(
            world,
            next_state,
            env.GRID_SIZE,
            animate=True,
        )

        if not render_for(
            world,
            MOVE_DISPLAY_SECONDS,
        ):
            return False

        state = next_state

        if terminated:
            print("-" * 50)
            print(f"Episode Terminated: {state}")
            state = get_random_start_state()
            print(f"Restarting next episode: from state: {state}")
            print("-" * 50)

    print(f"Episode stopped after nth " f"{MAX_EPISODE_STEPS} steps.")

    return render_for(
        world,
        END_DISPLAY_SECONDS,
    )


# ---------------------------------------------------------
# Console inspection
# ---------------------------------------------------------


def print_values(
    env: GridWorld4x4,
    values: dict[int, float],
) -> None:
    """Print Vπ as the same 4x4 layout as the environment."""

    print("\nState values Vπ:")

    for row in range(env.GRID_SIZE):

        row_values = []

        for column in range(env.GRID_SIZE):
            state = row * env.GRID_SIZE + column

            row_values.append(f"{values[state]:7.2f}")

        print(" ".join(row_values))


# ---------------------------------------------------------
# Complete visual policy iteration
# ---------------------------------------------------------


def play_and_render() -> None:
    """
    Run and visually demonstrate complete policy iteration.
    """

    env = GridWorld4x4()

    world = GridWorld(
        grid_size=env.GRID_SIZE,
        robot_start_position=state_to_position(
            get_random_start_state(),
            env.GRID_SIZE,
        ),
        render_title=("Sutton & Barto — Policy Iteration"),
    )

    # π₀
    policy: Policy = EquiprobableRandomPolicy(env)

    iteration = 0

    try:

        while True:

            print()
            print("=" * 60)
            print(f"POLICY ITERATION {iteration}")
            print("=" * 60)

            # -------------------------------------------------
            # 1. POLICY EVALUATION
            # -------------------------------------------------

            print("\nEvaluating current policy...")

            values = iterative_policy_evaluation(
                env=env,
                policy=policy,
                gamma=GAMMA,
                theta=THETA,
            )

            print_values(
                env,
                values,
            )

            # -------------------------------------------------
            # 2. DEMONSTRATE CURRENT POLICY
            # -------------------------------------------------

            print("\nDemonstrating current policy...")

            if not play_episode(
                env=env,
                policy=policy,
                world=world,
                start_state=get_random_start_state(),
                iteration=iteration,
            ):
                return

            # -------------------------------------------------
            # 3. POLICY IMPROVEMENT
            # -------------------------------------------------

            print("\nImproving policy...")

            improved_policy = improve_greedy_policy(
                env=env,
                vpi_values=values,
                gamma=GAMMA,
            )

            # -------------------------------------------------
            # 4. POLICY STABILITY
            # -------------------------------------------------

            stable = check_policies_equal(
                env,
                policy,
                improved_policy,
            )

            if stable:
                print()
                print("=" * 60)
                print("POLICY IS STABLE")
                print("=" * 60)

                print("\nFinal policy demonstration...")

                play_episode(
                    env=env,
                    policy=improved_policy,
                    world=world,
                    start_state=get_random_start_state(),
                    iteration=iteration,
                )

                print("\nPolicy iteration finished.")

                break

            print(
                "\nPolicy changed." "\nImproved policy becomes " "the current policy."
            )

            # πₖ ← πₖ₊₁
            policy = improved_policy

            iteration += 1

    finally:
        world.render_close()


# ---------------------------------------------------------
# Entry point
# ---------------------------------------------------------


if __name__ == "__main__":
    play_and_render()
